### ISSUE TITLE
UX Changes For Advanced Commands & Tasks (formerly Proposals)

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#190]
Notes:
- [x] Change proposals to tasks
- [ ] Merge my account into tasks
- [ ] "Create project" should move to the project menu
- [ ] "My Account" details displayed in Tasks menu 
- [ ] "I'd like command" moved to task actions as "Suggest an improvement to Swarmbot"
- [ ] Delete advanced commands menu item (award command totally deleted)

## Column 1

**projects » swarmbot-lovers**
*Project description goes here... this is currently not displayed anywhere*

**Tasks**
A: more hawaii vacations :thumbsup: 200 :moneybag: 2000
B: duke :thumbsup: 27 :moneybag: 200

## Column 2

**Account**
:moneybag: 3000
Bitcoin Address: [1PbT49i...](http://coloredcoins.org/explorer/address/1Eheyrg9iGc9YAU4M9LqbQ29m48MK2voUS)

**Actions**
0: projects
1: create a task
2: set bitcoin address
3: cap table
4: suggest a Swarmbot improvement
