### ISSUE TITLE
Epic: *All Projects* menu changes

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#193]
- [x] Has a welcome message at the top "Contribute to projects and get rewarded with project coins!"
- [x] User's first menu should be all projects. 
- [ ] Has a column showing "Your Project Coins". Only shows balances above 0. 
- [x] combine blue and yellow areas into one

[project name] :moneybag: [balance]

**Comment by aquabu** [comment]
![artboard 1 copy 2](https://cloud.githubusercontent.com/assets/7595/11483771/299db3e8-975f-11e5-8211-a61096c6ff7a.png)

![artboard 1 copy](https://cloud.githubusercontent.com/assets/7595/11483743/02bd9e96-975f-11e5-94f5-7acd380c2335.png)

![artboard 1](https://cloud.githubusercontent.com/assets/7595/11483736/f5fbceb2-975e-11e5-8789-85e4441ab3b2.png)

**Comment by dukedorje** [comment]
Suggest:  "Contribute to projects and receive project coins!"  'get rewarded' feels kind of patronizing somehow.... hard to quantify.

**Comment by Jay-TechSalon** [comment]
yeah, I hear you @duke

**Comment by harlantwood** [comment]
@aquabu + Jay --- @dukedorje and I are in dispute over whether to add `(Use letters and numbers to navigate)` as requested.
