### ISSUE TITLE
"Project View" UX Refresh

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#212]
- [x] user can create award
- [x] upon project creator, user can enter task management link
- [x] admin/progenitor can award a contribution
- [x] award list
- [x] show current project coins
- [x] review mockups, make sure all is done

**Comment by Jay-TechSalon** [comment]
![all projects project view copy 2](https://cloud.githubusercontent.com/assets/7764167/11573370/c830fae4-99ba-11e5-879d-250c3663fc61.png)
![all projects project view copy 3](https://cloud.githubusercontent.com/assets/7764167/11573372/c8362dc0-99ba-11e5-87c7-b698a3d07a3d.png)
![all projects project view](https://cloud.githubusercontent.com/assets/7764167/11573371/c8353e56-99ba-11e5-9f65-05ceb4db7a73.png)

**Comment by aquabu** [comment]
I'm breaking out a few missing elements into new issues.
